# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='request_type',
            field=models.CharField(default='PRODUCT', max_length=40),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_type',
            field=models.CharField(default='SERVICE', max_length=40),
        ),
    ]
