# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0002_auto_20170619_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
