# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0003_servicerequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='notification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
