# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0008_auto_20170619_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='itemmapt_ref',
            new_name='itemmap_ref',
        ),
    ]
