# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0010_review_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorderhistory',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='review_written',
            field=models.BooleanField(default=False),
        ),
    ]
