# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0011_auto_20170619_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='itemhistory_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewitemhistory', to='onelinkapp.ItemOrderHistory'),
        ),
        migrations.AlterField(
            model_name='review',
            name='servicehistory_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewservicehistory', to='onelinkapp.OrderHistory'),
        ),
    ]
