# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0012_auto_20170619_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorderhistory',
            name='service_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='service_status',
            field=models.IntegerField(default=1),
        ),
    ]
