# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0013_auto_20170620_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='final_budjet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='final_budjet',
            field=models.FloatField(default=0),
        ),
    ]
