# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0014_auto_20170620_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrequest',
            old_name='final_budjet',
            new_name='final_budget',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='final_budjet',
            new_name='final_budget',
        ),
    ]
