# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0016_auto_20170621_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmap',
            name='itemmap_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemap',
            name='servicemap_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
