# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0017_auto_20170627_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmap',
            old_name='item_image',
            new_name='itemmap_image1',
        ),
        migrations.RenameField(
            model_name='itemmap',
            old_name='itemmap_image',
            new_name='itemmap_image2',
        ),
        migrations.AddField(
            model_name='itemmap',
            name='itemmap_image3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemmap',
            name='itemmap_image4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemmap',
            name='itemmap_image5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
