# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-30 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0018_auto_20170629_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='request_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
