# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0019_servicerequest_request_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='building',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='street',
            field=models.TextField(blank=True, null=True),
        ),
    ]
