# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0020_auto_20170703_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='service_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicemap',
            name='service_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicenotification',
            name='service_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='servicemap',
            name='license_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='servicemap',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicemap',
            name='service_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicemap',
            name='service_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='servicemap',
            name='under_gov',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
