# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0021_auto_20170704_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
