# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0022_auto_20170704_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemorderhistory',
            old_name='service_status',
            new_name='item_status',
        ),
    ]
