# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import onelinkapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_id', models.IntegerField()),
                ('serviceprovider_email', models.EmailField(max_length=254)),
                ('service_category_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=500)),
                ('item_details', models.TextField()),
                ('item_features', models.TextField()),
                ('areapincode', models.PositiveIntegerField()),
                ('iteme_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=onelinkapp.models.item_image_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('item_MRP', models.FloatField()),
                ('item_SLP', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=500)),
                ('service_detail', models.TextField()),
                ('service_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=onelinkapp.models.service_image_upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=500)),
                ('service_details', models.TextField()),
                ('serviceprovider_email', models.EmailField(max_length=254)),
                ('service_category_id', models.IntegerField()),
                ('areapincode', models.PositiveIntegerField()),
                ('service_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onelinkapp.ServiceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_service_name', models.CharField(max_length=500)),
                ('sub_service_detail', models.TextField()),
                ('service_categorgy_id', models.IntegerField()),
                ('service_categorgy_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onelinkapp.ServiceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('pincode', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('key', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('user_type', models.IntegerField(default=0)),
                ('user_createtime', models.DateTimeField(auto_now_add=True)),
                ('validemail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('full_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('User_Type', models.IntegerField()),
                ('UserSession_starttime', models.DateTimeField(auto_now_add=True)),
                ('UserSession_lastmodifiedtime', models.DateTimeField(auto_now=True)),
                ('UserDetail_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='onelinkapp.UserDetail')),
                ('UserDetail_id', models.IntegerField(unique=True)),
                ('UserSession_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerificationSession',
            fields=[
                ('full_name', models.CharField(max_length=500)),
                ('session_starttime', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('User_Type', models.IntegerField()),
                ('UserDetail_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='onelinkapp.UserDetail')),
                ('UserDetail_id', models.IntegerField(unique=True)),
                ('UserSession_key', models.CharField(max_length=200, unique=True)),
                ('verificationtype', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='itemmap',
            name='service_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onelinkapp.ServiceCategory'),
        ),
    ]
