# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onelinkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmap',
            old_name='iteme_image',
            new_name='item_image',
        ),
        migrations.RemoveField(
            model_name='itemmap',
            name='areapincode',
        ),
    ]
